login streak logic/ purchase screen / some small funcionality updates…
andreolikalcopoli/Trade-Coach pull request #2
Opened 2023-12-28 08:47 UTC by NemanjaDucic

… on home screen / community chat added

2023-12-28 12:46 UTC, andreolikalcopoli requested changes

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/model/ChatMessage.kt
Ovo treba da bude **data class**
Ne moras da imas konstruktor u tom slucaju

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/ui/fragments/community/chat/ChatFragment.kt
> +fun<T : Any, L : LiveData<T>> LifecycleOwner.observe(liveData: L, body: (T) -> Unit) {
Ovo ne bi smelo da bude deo random activity, izvadi ga u neki poseban fajl, u di package

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/ui/fragments/currencies/CurrenciesFragment.kt
> +        requireActivity().onBackPressedDispatcher.addCallback(this) {
sintaksa, mnogo praznih linija

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/ui/fragments/home/HomeFragment.kt
> +    private val viewModel: MainViewModel by viewModels()
Zasto **by viewModels()**? Valjda **by viewModel()**

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/ui/segmentPurchase/PurchaseAdapter.kt
> +        return 6
Ajde da napravimo da ovo bude konstanta, ne hardcoded

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/ui/segmentPurchase/PurchaseActivity.kt
> +        binding.purchaseRecyclerView.layoutManager = GridLayoutManager(this,3)
Ajde da napravimo da ovo bude konstanta, ne hardcoded

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/utilities/Utils.kt
> +    fun setFragment(activity: FragmentActivity, fragment: Fragment, position: Int) {
Odlicno, svidja mi se!

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/viewmodel/ChatViewModel.kt
> +        val query = FirebaseDatabase.getInstance().reference.child("chat").limitToLast(50)
50 da napravimo da je constant, ne hardcoded

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/viewmodel/ChatViewModel.kt
> +    private fun setAvatarInitials(username: String, imageView: ImageView) {
Ovo izdvoji u utils, jos iz tesle ga mrzim

2023-12-28 12:46 UTC, andreolikalcopoli commented on app/src/main/java/com/magma/tradecoach/viewmodel/ChatViewModel.kt
> +    private fun splitTime(time: String): String {
izdvoji u utils

2024-01-11 08:16 UTC, NemanjaDucic commented on app/src/main/java/com/magma/tradecoach/ui/fragments/home/HomeFragment.kt
> +    private val viewModel: MainViewModel by viewModels()
hilt sintaksa je takva

2024-01-11 09:20 UTC, andreolikalcopoli approved these changes

2024-01-17 07:57 UTC, merged